Entity/CompletedQuestionnaireInterface.php
<?php
/**
 * @package Extra_QuestionnaireBundle
 * @author  Lubo Grozdanov <grozdanov.lubo@gmail.com>
 */

namespace Extra\QuestionnaireBundle\Entity;


/**
 * Interface CompletedQuestionnaireInterface
 * @package Extra\QuestionnaireBundle\Entity
 * @author  Lubo Grozdanov <grozdanov.lubo@gmail.com>
 */
interface CompletedQuestionnaireInterface
{
    /**
     * @return int
     */
    public function getId();

    /**
     * @return string
     */
    public function getUserData();

    /**
     * @return string
     */
    public function getQuestionnaireData();

}

Resources/views/Admin/list_user_data.html.twig
{% extends 'SonataAdminBundle:CRUD:base_list_field.html.twig' %}

{% block field %}
    <table class="table">
        <thead>
        <tr>
            {% for key, value in object.userData %}
                <td>{{ key }}</td>
            {% endfor %}
        </tr>
        </thead>
        <tbody>
        <tr>
            {% for value in object.userData %}
                <td>
                    {% if value is iterable %}
                        {{ value|join }}
                    {% else %}
                        {{ value }}
                    {% endif %}
                </td>
            {% endfor %}
        </tr>
        </tbody>
    </table>
{% endblock %}

Resources/views/Admin/show_questionnaire_data.html.twig
{% extends 'SonataAdminBundle:CRUD:base_show_field.html.twig' %}

{% block field %}
    {% set questionnaireData = object.questionnaireData %}
    {% if questionnaireData['title'] is defined %}
        <tr>
            <th colspan="7" class="text-center">
                {{ questionnaireData['title'] }}
            </th>
        </tr>
    {% endif %}

    <tr>
        <th class="text-center" colspan="3">
            {{ 'extra_questions'|trans({}, 'ExtraQuestionnaireBundle') }}
        </th>
        <th class="text-center" colspan="4">
            {{ 'extra_answers'|trans({}, 'ExtraQuestionnaireBundle') }}
        </th>
    </tr>

    {% if questionnaireData['questions'] is defined %}
        {% for question in questionnaireData['questions'] %}
            {% if question['title'] is defined and question['answers'] is defined %}
                <tr>
                    <th colspan="3">
                        {{ question['title'] }}
                    </th>
                    <th colspan="4">
                        {% for answer in question['answers'] %}
                            {% if answer['title'] is defined %}
                                <p class="{% if answer['checked'] %} bg-success {% endif %} text-center table-bordered">
                                    {{ answer['title'] }}
                                </p>
                            {% endif %}
                        {% endfor %}
                    </th>
                </tr>
            {% endif %}
        {% endfor %}
    {% endif %}
{% endblock %}

Resources/views/Admin/show_user_data.html.twig
{% extends 'SonataAdminBundle:CRUD:base_show_field.html.twig' %}

{% block field %}
    <tr>
        {% for key, value in object.userData %}
            <td>{{ key }}</td>
        {% endfor %}
    </tr>
    <tr>
        {% for value in object.userData %}
            <td>
                {% if value is iterable %}
                    {{ value|join }}
                {% else %}
                    {{ value }}
                {% endif %}
            </td>
        {% endfor %}
    </tr>
{% endblock %}